### ISSUE TITLE
Ball rolls in wrong direction - Bugs Bunny's Birthday Ball (Bally 1991)Rev2.3b

### ISSUE THREAD

**Issue by francisdb** [jsm174/vpx-standalone-scripts#13]
Just keeping track of this issue here

Bugs Bunny when I start the game the ball just rolls to the table end and stays there. Looks like the inclination of the table is off.

**Comment by francisdb** [comment]
This version does not have the issue:

`Bugs Bunny's Birthday Ball (Balutito Reskin)`

Looking at a diff for the script but it's big

**Comment by jsm174** [comment]
Finally had a chance to research this. 

The table was using a `PhysicsSet` with a value of 4:

![Screenshot 2023-07-06 at 11 10 31 PM](https://github.com/jsm174/vpx-standalone-scripts/assets/1197137/b2a9bcd4-6b2e-40ed-a0a4-486245432365)

The `PhysicsSets` get defaulted when they don't exist in the `VPinballX.ini` file. There was a bug where `m_fOverrideGravityConstant` was not being pulled from `live_table` and was ending up as `0`, thus the ball floating up the table.

```patch
--- a/pintable.cpp
+++ b/pintable.cpp
@@ -2628,10 +2628,10 @@ void PinTable::Play(const bool cameraMode)
       PLOGI << "Creating main window"; // For profiling
       g_pplayer = new Player(cameraMode, this, live_table);
       g_pplayer->CreateWnd();
-      const float minSlope = (m_overridePhysics ? m_fOverrideMinSlope : m_angletiltMin);
-      const float maxSlope = (m_overridePhysics ? m_fOverrideMaxSlope : m_angletiltMax);
+      const float minSlope = (m_overridePhysics ? live_table->m_fOverrideMinSlope : m_angletiltMin);
+      const float maxSlope = (m_overridePhysics ? live_table->m_fOverrideMaxSlope : m_angletiltMax);
       const float slope = minSlope + (maxSlope - minSlope) * m_globalDifficulty;
-      g_pplayer->SetGravity(slope, m_overridePhysics ? m_fOverrideGravityConstant : m_Gravity);
+      g_pplayer->SetGravity(slope, m_overridePhysics ? live_table->m_fOverrideGravityConstant : m_Gravity);

       m_vpinball->ToggleToolbar();
```       

This is now fixed in the latest version of standalone.

**Comment by francisdb** [comment]
Great find!
I guess this relates to https://github.com/vpinball/vpinball/pull/621 ?

**Comment by jsm174** [comment]
yup! glad this one is wrapped up!
