### ISSUE TITLE
No DMD for "Avengers Pro (Stern 2012) MOD.vpx"

### ISSUE THREAD

**Issue by francisdb** [jsm174/vpx-standalone-scripts#6]
Desktop mode

Same with `Avengers Pro (Stern 2012)_Bigus(MOD)1.3.vpx`

**Comment by jsm174** [comment]
*Background:*

Regular VPX uses VPinMAME to draw the DMD. VPinMAME is technically a separate process that is capable of drawing it's own borderless window on top of VPX. 

VPX does has the ability to draw a DMD into the scene using a `textbox` or a `flasher` object. These objects have a `dmd` boolean property. 

From what I can tell, textboxes are usually used on the desktop, while flashers are used when in VR.

- Textboxes look good on a wide screen, but they appear skewed on the phone in portrait mode. 

- Flashers seem to have more capability and can be rotated. (I've had difficulty trying to position them flat in the left corner of the screen)

Anyway, with that said, some tables have textboxes for the DMD turned on and visible in desktop, but many do not. Sometimes they are called `Textbox`, `DMD`, `scoretext`.

*Solution:*

Since standalone does not have an editor we can't easily add or modify these in the vpx file, we inject an invisible textbox into all tables at runtime called `ImplicitDMD`.

To enable it, look for `LoadVPM` and above it, put this block of code in:

```
Sub ImplicitDMD_Init
   Me.x = 30
   Me.y = 30
   Me.width = 128 * 2
   Me.height = 32 * 2
   Me.visible = true
End Sub
```

If you still don't see a DMD, you'll need to look for: `UseVPMDMD` or `UseVPMColoredDMD`. One of these are required to fetch the DMD pixels from VPinMAME to will get rendered into the textbox.

Note: If you're using a Serum colorization file, you must use `UseVPMColoredDMD`

*Finally:*

This repo is only about the bare minimum vbscript changes required to get a table to run under standalone. Adding `ImplicitDMD` is just a hack and could later change, so I didn't want them in these files (especially if an author looks here to see how to fix table for standalone). Sorry.

**Comment by francisdb** [comment]
Thanks for explaining. Now you can point other ppl here :-)

**Comment by francisdb** [comment]
specific fix for avengers pro:

```diff
--- /tables/Avengers Pro (Stern 2012) MOD.vbs.original.tmp 2023-06-07 20:08:03
+++ /tables/Avengers Pro (Stern 2012) MOD.vbs      2023-06-07 19:44:55
@@ -30,6 +30,16 @@
 ExecuteGlobal GetTextFile("controller.vbs")
 If Err Then MsgBox "You need the Controller.vbs file in order to run this table (installed with the VPX package in the scripts folder)"
 On Error Goto 0
+
+Sub ImplicitDMD_Init
+   Me.x = 30
+   Me.y = 30
+   Me.width = 128 * 2
+   Me.height = 32 * 2
+   Me.visible = true
+End Sub
+
+Const UseVPMDMD = True
 
 LoadVPM "01560000", "sam.VBS", 3.10
```
